In [18]:
import numpy as np
from itertools import permutations

In [17]:
#number of drivers
D = 3

#driver name - encoding
driver_id = {0: 'Lando Norris', 1: 'Max Verstappen', 2: 'Oscar Piastri'}

#Points available (0 depicts out of points or DNF or DSQ)
points = np.array([25, 18, 15, 12, 10, 8, 6, 4, 2, 1, 0])

#Ranks they can finish at
ranks = np.array([i for i in range(0, 12)])

In [71]:
# 3 drivers can finish in 11 places. (7290 x 3) size matrix of possibilities

def finishing_permutations(maximum):
    res = np.zeros(shape=(7290, 4), dtype=int)

    for i in range(len(ranks)):
        for j in range(3):
            res[i][j] = ranks[j]
            print(res)

In [72]:
finishing_permutations(D)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 0]
 [0 1 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 0]
 [0 1 2 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 0]
 [0 1 2 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 0]
 [0 1 2 0]
 [0 1 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 0]
 [0 1 2 0]
 [0 1 2 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 0]
 [0 1 2 0]
 [0 1 2 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 0]
 [0 1 2 0]
 [0 1 2 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 0]
 [0 1 2 0]
 [0 1 2 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 0]
 [0 1 2 0]
 [0 1 2 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 2 0]
 [0 1 2 0]
 [0 1 2 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 

In [60]:
ranks[0:3]

array([0, 1, 2])