import numpy as np

In [2]:
def factorial(num):
    if num==0:
        return 1
    else:
        return num*(factorial(num-1))

def isOdd(N): return N%2



CAN ONLY CALCULATE FOR THE PODIUM PLACES.

I BELIEVE MOST OF IT IS CALCULATED $WRONG$ AS WELL

GIVES SOME EXTRA POINTS TO DRIVERS SOMEHOW (MICHAEL MASI GET OUT OF MY LAPTOP)



In [28]:
def possibilities(ranks):
    arr = ranks
    m = 3
    n = factorial(m)
    p = np.zeros(shape=(n, m), dtype=int)
    p[0] = arr
    print(p[0])
    for i in range(1, n):
        if isOdd(i):
            #SET FIRST ELMT IN ROW SAME AS ABOVE
            p[i][0] = p[i-1][0]
            #SWAP
            p[i][1] = p[i-1][2]
            p[i][2] = p[i-1][1]
            print(p[i])
        else:
            #p[i] = arr + 1
            for j in range(0,3):
                p[i][j] = p[i-2][j]+1
            p[i] %= max(ranks)
            print(p[i])
    print(type(p))
    return p

In [29]:
"""
    0: Lando Norris
    1: Max Verstappen
    2: Oscar Piastri
"""

def points_allotment(fin_pos, driver_id, standings):
    
    points = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1]
    # print(f'Driver {driver_id} scores {points[fin_pos]}')
    standings[driver_id] += points[fin_pos]

    return standings    

In [31]:
# points = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1]

drivers = {0: 'Lando Norris', 1: 'Max Verstappen', 2: 'Oscar Piastri'}


fin_ranks = np.array([0, 1, 2])
p = possibilities(fin_ranks)
    
for i in range(0, 6):
    
    print("\nPermutation", i+1)
        
    standings = [408, 396, 392]
    
    for j in range(0, 3):
        standings = points_allotment(p[i][j], j, standings)
        
    print(standings)
    print("Position | Driver | Points")
    print("--------------------------")
        
    for k in range(0, 3):
        print(f'{k}  |  {drivers[p[i][k]]}  |  {standings[k]}')
        
    print("--------------------------")
        
    winner = standings.index(max(standings))
    print(f'\t\t{drivers[winner]} WINS THE 2025 FORMULA 1 CHAMPIONSHIP')
        
    print("--------------------------")

[0 1 2]
[0 2 1]
[1 0 1]
[1 1 0]
[0 1 0]
[0 0 1]
<class 'numpy.ndarray'>

Permutation 1
[433, 414, 407]
Position | Driver | Points
--------------------------
0  |  Lando Norris  |  433
1  |  Max Verstappen  |  414
2  |  Oscar Piastri  |  407
--------------------------
		Lando Norris WINS THE 2025 FORMULA 1 CHAMPIONSHIP
--------------------------

Permutation 2
[433, 411, 410]
Position | Driver | Points
--------------------------
0  |  Lando Norris  |  433
1  |  Oscar Piastri  |  411
2  |  Max Verstappen  |  410
--------------------------
		Lando Norris WINS THE 2025 FORMULA 1 CHAMPIONSHIP
--------------------------

Permutation 3
[426, 421, 410]
Position | Driver | Points
--------------------------
0  |  Max Verstappen  |  426
1  |  Lando Norris  |  421
2  |  Max Verstappen  |  410
--------------------------
		Lando Norris WINS THE 2025 FORMULA 1 CHAMPIONSHIP
--------------------------

Permutation 4
[426, 414, 417]
Position | Driver | Points
--------------------------
0  |  Max Verstap